import type { Metadata } from 'next'
import './globals.css'
import Head from 'next/head';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <title>Pagamento GRU UFJ</title>
      </head>
      <body >{children}</body>
    </html>
  )
}
